5th task
js-tasks-ru/vue-20210119_aior pull request #4
Opened 2021-02-20 11:27 UTC by Azginar

split meetup page on module

2021-02-20 11:27 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-02-22 11:13 UTC, ShGKme requested changes
Требуется немного поправить работу с изображением

2021-02-22 11:13 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupCover.js
> +  template: `<div class="meetup-cover" :style="link ? \`--bg-url: url('\${link}')\` : 'https://course-vue.javascript.ru/api/images/2'">
В случае отсутствия ссылки в style устанавливается `style="https://course-vue.javascript.ru/api/images/2"`.
Это инвалидный style для HTML.

В случае отсутствия на изображение, не требуется никак изменять стили. Изображение по умолчанию уже установлено в `--bg-url` в стилях. Если изображение есть, то ссылку на него устанавливается в инлайн-стилях в  `--bg-url`, переопределяя значение по умолчанию с дефолтным изображением. Если нет - ничего делать не требуется.

2021-02-22 11:13 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupPage.js
> +  },
Это вычисляемое свойство не нужно и не используется.

2021-02-22 11:13 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupView.js
> +    },
Если изображения нет, то `linkImage` вернёт некорректную ссылку `/api/images/null`. Требуется делать здесь проверку, и не использовать `getMeetupCoverLink`, если изображения нет. Можно также изменить функцию `getMeetupCoverLink`.

2021-03-01 19:29 UTC, ShGKme approved these changes
Все задачи приняты 👍

2021-03-01 19:29 UTC, ShGKme commented on 03-vue-cli/01-CounterButton-vue/components/CounterButton.vue
> +    }
Лучше не присваивать новые значения в переменные, хранящие значение параметров функции.
Здесь достаточно вызвать `$emit`, передав в него `newValue + 1`.

2021-03-01 19:29 UTC, merged